services:
  db:
    image: postgis/postgis:16-3.4
    container_name: aidflow_postgres
    environment:
      POSTGRES_USER: aidflow_user
      POSTGRES_PASSWORD: aidflow_password
      POSTGRES_DB: aidflow_db
    ports:
      - "5432:5432"
    volumes:
      - aidflow_postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: aidflow_backend
    environment:
      DATABASE_URL: postgresql://aidflow_user:aidflow_password@db:5432/aidflow_db
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  aidflow_postgres_data: