"""create aid requests table

Revision ID: 47aa58aa2b90
Revises: 5b8851c820ad
Create Date: 2026-06-23 08:26:04.021514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '47aa58aa2b90'
down_revision: Union[str, Sequence[str], None] = '5b8851c820ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aid_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'AI_REVIEWED', 'ADMIN_APPROVED', 'ADMIN_REJECTED', 'ASSIGNED_TO_VOLUNTEER', 'VERIFIED', 'VERIFICATION_REJECTED', 'CLAIMED', 'FULFILLED', name='aid_request_status'), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('ai_urgency', sa.String(length=50), nullable=True),
    sa.Column('ai_missing_fields', sa.Text(), nullable=True),
    sa.Column('ai_risk_indicators', sa.Text(), nullable=True),
    sa.Column('ai_verification_checklist', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aid_requests_requester_id'), 'aid_requests', ['requester_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_aid_requests_requester_id'), table_name='aid_requests')
    op.drop_table('aid_requests')
    # ### end Alembic commands ###
