"""add proof fields to aid requests

Revision ID: 687bcf62ada4
Revises: 80aecae431be
Create Date: 2026-06-25 07:37:31.629647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '687bcf62ada4'
down_revision: Union[str, Sequence[str], None] = '80aecae431be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aid_requests', sa.Column('proof_url', sa.String(length=1000), nullable=True))
    op.add_column('aid_requests', sa.Column('proof_notes', sa.Text(), nullable=True))
    op.add_column('aid_requests', sa.Column('proof_uploaded_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('aid_requests', 'proof_uploaded_at')
    op.drop_column('aid_requests', 'proof_notes')
    op.drop_column('aid_requests', 'proof_url')
    # ### end Alembic commands ###
