"""add donor claim fields to aid requests

Revision ID: 80aecae431be
Revises: 9439d55e23b4
Create Date: 2026-06-24 08:59:55.977882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80aecae431be'
down_revision: Union[str, Sequence[str], None] = '9439d55e23b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('aid_requests', sa.Column('claimed_by_donor_id', sa.UUID(), nullable=True))
    op.add_column('aid_requests', sa.Column('claimed_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'aid_requests', 'users', ['claimed_by_donor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'aid_requests', type_='foreignkey')
    op.drop_column('aid_requests', 'claimed_at')
    op.drop_column('aid_requests', 'claimed_by_donor_id')
    # ### end Alembic commands ###
