"""create verification tasks table

Revision ID: 9439d55e23b4
Revises: 47aa58aa2b90
Create Date: 2026-06-24 08:28:47.430014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9439d55e23b4'
down_revision: Union[str, Sequence[str], None] = '47aa58aa2b90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verification_tasks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('aid_request_id', sa.UUID(), nullable=False),
    sa.Column('volunteer_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ASSIGNED', 'VERIFIED', 'REJECTED', name='verification_task_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['aid_request_id'], ['aid_requests.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_tasks_aid_request_id'), 'verification_tasks', ['aid_request_id'], unique=False)
    op.create_index(op.f('ix_verification_tasks_volunteer_id'), 'verification_tasks', ['volunteer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_tasks_volunteer_id'), table_name='verification_tasks')
    op.drop_index(op.f('ix_verification_tasks_aid_request_id'), table_name='verification_tasks')
    op.drop_table('verification_tasks')
    # ### end Alembic commands ###
